# Generated by Django 6.0.5 on 2026-05-30 03:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24),
        ),
        migrations.AddField(
            model_name='wallet',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('SOL', 'Solana'), ('BNB', 'Binance Coin'), ('DOGE', 'Dogecoin')], default='BTC', max_length=6),
        ),
    ]
