# Generated by Django 6.0.5 on 2026-05-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_wallet_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('SOL', 'Solana'), ('BNB', 'Binance Coin'), ('DOGE', 'Dogecoin'), ('XRP', 'XRP'), ('ADA', 'Cardano'), ('POL', 'POL (ex‑MATIC)'), ('AVAX', 'Avalanche'), ('LTC', 'Litecoin')], default='BTC', max_length=6),
        ),
    ]
